# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-02 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20171218_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
